blog/urls.py
from django.urls import path, include
from .views import api, api2, page
app_name = 'blog'

urlpatterns = [
	path('', page.show_index, name='index'),
	path('new/', page.create_post, name='create_post'),
	path('<int:id>/', page.view_post, name='view_post'),
	path('<int:id>/edit', page.edit_post, name='edit_post'),
    
    path('api2/', include(api2.router.urls)),
    
	path('api/post', api.list_posts, name='api_list_posts'),
	path('api/post/new', api.create_post, name='api_create_post'),
	path('api/post/<int:post_id>', api.get_post, name='api_get_post'),
    path('api/post/<int:post_id>/edit', api.edit_post, name="api_edit_post"),
    path('api/post/<int:post_id>/delete', api.delete_post, name="api_delete_post"),
	path('api/post/<int:post_id>/comment', api.list_comments, name="api_list_comments"),
	path('api/post/<int:post_id>/comment/new', api.create_comment, name="api_create_comment"),
    path('api/post/<int:post_id>/comment/<int:comment_id>', api.get_comment, name="api_get_comment"),
    path('api/post/<int:post_id>/comment/<int:comment_id>/edit', api.edit_comment, name="api_edit_comment"),
    path('api/post/<int:post_id>/comment/<int:comment_id>/delete', api.delete_comment, name="api_delete_comment")
]

faq/urls.py
from django.urls import path
from .views import index, json, add, update_thumbsUp,  Add_from_flutter

app_name = 'faq'
urlpatterns = [
    path('', index, name='index'),
    path('json/', json, name='json'),
    path('add/', add, name='add'),
    path('thumbsup/', update_thumbsUp, name='update_thumbsUp'),
    path('addFlutter/', Add_from_flutter, name ='Add_from_flutter')

]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('bank/', include('banksampah.urls')),
    path('blog/', include('blog.urls')),
    path('faq/', include('faq.urls')),
    path('auth/', include('authc.urls')),
    path('report/', include('crewdashboard.urls')),
]


blog/models.py
from django.db import models
from authc.models import User

class Post(models.Model):
	author = models.ForeignKey(User, on_delete=models.CASCADE)
	title = models.TextField()
	content = models.TextField()
	created_timestamp = models.DateTimeField(auto_now_add=True)
	modified_timestamp = models.DateTimeField(auto_now=True)

	class Meta:
		permissions = [
			("change_self_post", "Can edit posts made by the user"),
			("change_other_post", "Can edit posts made by other users"),
			("delete_self_post", "Can delete posts made by the user"),
			("delete_other_post", "Can delete posts made by other users"),
		]

	def __str__(self) -> str:
		return str(self.title)
	
class Comment(models.Model):
	author = models.ForeignKey(User, on_delete=models.CASCADE)
	content = models.TextField()
	post = models.ForeignKey(Post, on_delete=models.CASCADE)
	created_timestamp = models.DateTimeField(auto_now_add=True)
	modified_timestamp = models.DateTimeField(auto_now=True)

	class Meta:
		permissions = [
			("change_self_comment", "Can edit comments made by the user"),
			("change_other_comment", "Can edit comments made by other users"),
			("delete_self_comment", "Can delete comments made by the user"),
			("delete_other_comment", "Can delete comments made by other users")
		]

	def __str__(self) -> str:
		return str(self.pk)

blog/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content']

    def __str__(self):
        return ""
    
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

    def __str__(self):
        return ""

blog/views/api.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.core import serializers
from django.utils import timezone
from django.core.paginator import Paginator, EmptyPage
from authc.models import User
from blog.forms import PostForm, CommentForm
from blog.models import Post, Comment
from datetime import date, datetime
from django.views.decorators.csrf import csrf_exempt
import bleach
import json

def HttpResponseJson(json_obj, **kwargs):
	return HttpResponse(json.dumps(json_obj), content_type="application/json", **kwargs)

def apires_ok(data={"status": "OK"}):
	return HttpResponseJson(data, status=200)

def apires_created(data={"status": "Created"}):
	return HttpResponseJson(data, status=201)

def apires_bad_request(data={"status": "Bad Request"}):
	return HttpResponseJson(data, status=400)

def apires_unauthorized(data={"status": "Forbidden"}):
	return HttpResponseJson(data, status=403)

def apires_not_found(data={"status": "Not Found"}):
	return HttpResponseJson(data, status=404)

def object_to_json(data):
	return json.loads(serializers.serialize("json", [data]))[0]

def list_posts(request):
	if not request.method == "GET":
		return apires_bad_request([])

	posts = Post.objects.all()
	paginator = Paginator(posts, 10)
	page_number = request.GET.get('page') or 1
	
	return HttpResponse(serializers.serialize("json", paginator.get_page(page_number)), content_type="application/json")

def get_post(request, post_id):
	if not request.method == "GET":
		return apires_bad_request([])

	post = Post.objects.filter(pk=post_id).first()
	
	if not post:
		return apires_not_found([])
	
	return JsonResponse(object_to_json(post))

@csrf_exempt
def create_post(request):
	if not request.user.is_authenticated or not request.user.has_perm('blog.add_post'):
		return apires_unauthorized([])
	if not request.method == "POST":
		return apires_bad_request([])
	
	form = PostForm(request.POST or json.loads(request.body), instance=Post())

	if not form.is_valid():
		return apires_bad_request([])
	
	post = form.save(commit=False)
	post.title = bleach.clean(post.title)
	post.content = bleach.clean(post.content)
	post.author = request.user
	post.save()
	form.save_m2m()
	
	return apires_created(object_to_json(post))

@csrf_exempt
def edit_post(request, post_id):
	if not request.user.is_authenticated or not (request.user.has_perm('blog.change_other_post') or request.user.has_perm('blog.change_self_post')):
		return apires_unauthorized()
	if not request.method == "POST":
		return apires_bad_request()
	
	post = Post.objects.filter(pk=post_id).first()

	if not post:
		return apires_bad_request()
	if not request.user.has_perm('blog.change_other_post'):
		if not request.user != post.author:
			return apires_unauthorized()

	data = request.POST or json.loads(request.body)

	post.title = bleach.clean(data['title'])
	post.content = bleach.clean(data['content'])
	post.save()

	return apires_ok(object_to_json(post))

@csrf_exempt
def delete_post(request, post_id):
	if not request.user.is_authenticated or not (request.user.has_perm('blog.delete_other_post') or request.user.has_perm('blog.delete_self_post')):
		return apires_unauthorized()
	if not request.method == "DELETE":
		return apires_bad_request()
	
	post = Post.objects.filter(pk=post_id).first()

	if not post:
		return apires_bad_request()
	if not request.user.has_perm('blog.delete_other_post'):
		if not request.user != post.author:
			return apires_unauthorized()

	post.delete()

	return apires_ok()

def list_comments(request, post_id):
	if not request.method == "GET":
		return apires_bad_request([])
	
	post = Post.objects.filter(pk=post_id).first()

	if not post:
		return apires_not_found([])
	
	comments_all = Comment.objects.filter(post=post)
	paginator = Paginator(comments_all, 10)
	page_number = request.GET.get('page') or 1
	
	try:
		comments = json.loads(serializers.serialize("json", paginator.page(page_number)))
	except EmptyPage:
		return apires_ok([])
		
	for comment in comments:
		
		user = User.objects.get(pk=comment['fields']['author'])

		comment['fields']['author'] = {
			'username': user.username,
			'name': user.name,
		}

		comment['perms'] = {
			'edit': (user == request.user and request.user.has_perm('blog.change_self_comment')) or request.user.has_perm('blog.change_other_comment'),
			'delete': (user == request.user and request.user.has_perm('blog.delete_self_comment')) or request.user.has_perm('blog.delete_other_comment'),
		}

	return apires_ok(comments)

def get_comment(request, post_id, comment_id):
	if not request.method == "GET":
		return apires_bad_request([])
	
	post = Post.objects.filter(pk=post_id).first()

	if not post:
		return apires_not_found([])
	
	comment = Comment.objects.filter(post=post, pk=comment_id).first()

	return apires_ok(object_to_json(comment))

@csrf_exempt
def create_comment(request, post_id):
	if not request.user.is_authenticated or not request.user.has_perm('blog.add_comment'):
		return apires_unauthorized()
	if not request.method == "POST":
		return apires_bad_request()
	
	post = Post.objects.filter(pk=post_id).first()

	if not post:
		return apires_not_found()

	form = CommentForm(request.POST or json.loads(request.body), instance=Comment())

	if not form.is_valid():
		return apires_bad_request()
	
	comment = form.save(commit=False)
	comment.content = bleach.clean(comment.content)
	comment.author = request.user
	comment.post = post
	comment.save()
	form.save_m2m()

	return apires_created(object_to_json(comment))

@csrf_exempt
def edit_comment(request, post_id, comment_id):
	if not request.user.is_authenticated or not (request.user.has_perm('blog.change_other_comment') or request.user.has_perm('blog.change_self_comment')):
		return apires_unauthorized([])
	if not request.method == "POST":
		return apires_bad_request([])
	
	post = Post.objects.filter(pk=post_id).first()

	if not post:
		return apires_not_found([])
	
	comment = Comment.objects.filter(pk=comment_id).first()

	if not comment or not comment.post == post:
		return apires_bad_request([])
	if not request.user.has_perm('blog.change_other_comment'):
		if not request.user != post.author:
			return apires_unauthorized([])
		
	data = request.POST or json.loads(request.body)
	
	comment.content = bleach.clean(data['content'])
	comment.save()

	return apires_created(object_to_json(comment))

@csrf_exempt
def delete_comment(request, post_id, comment_id):
	if not request.user.is_authenticated or not (request.user.has_perm('blog.delete_other_comment') or request.user.has_perm('blog.delete_self_comment')):
		return apires_unauthorized()
	if not (request.method == "DELETE" or request.method == "POST"):
		print(request.post)
		return apires_bad_request()
	
	post = Post.objects.filter(pk=post_id).first()

	if not post:
		return apires_not_found()
	if not request.user.has_perm('blog.delete_other_comment'):
		if not request.user != post.author:
			return apires_unauthorized()
	
	comment = Comment.objects.filter(pk=comment_id).first()

	if not comment or not comment.post == post:
		return apires_not_found()
	
	comment.delete()

	return apires_ok()

blog/views/api2.py
from rest_framework import routers, serializers, viewsets, pagination, decorators, status
from rest_framework_extensions import routers as ext_routers, mixins as ext_mixins
from authc.models import User
from blog.forms import PostForm, CommentForm
from blog.models import Post, Comment
from rest_framework.response import Response

class StandardResultsSetPagination(pagination.PageNumberPagination):
    page_size = 10
    page_size_query_param = 'page_size'

class ReadOnlyModelSerializer(serializers.ModelSerializer):
    def get_fields(self, *args, **kwargs):
        fields = super().get_fields(*args, **kwargs)
        for field in fields:
            fields[field].read_only = True
        return fields
    # pass

class LimitedUserSerializer(ReadOnlyModelSerializer):
    username = serializers.CharField()
    name = serializers.CharField()

    class Meta:
        model = User
        fields = ['pk', 'username', 'name']

class PostSerializer(serializers.ModelSerializer):
    author = LimitedUserSerializer()

    class Meta:
        model = Post
        fields = ['pk', 'author', 'title', 'content', 'created_timestamp', 'modified_timestamp']
    
class PostViewSet(ext_mixins.NestedViewSetMixin, viewsets.ModelViewSet):
    queryset = Post.objects.all().order_by('-created_timestamp')
    serializer_class = PostSerializer
    pagination_class = StandardResultsSetPagination

    author = serializers.HiddenField(
        default=serializers.CurrentUserDefault(),
    )

    def create(self, request, *args, **kwargs):
        post = Post()
        post.author = request.user
        serializer = self.serializer_class(post, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    
class CommentSerializer(serializers.ModelSerializer):
    author = LimitedUserSerializer(required=False)

    # def perform_create(self, serializer):
    #     serializer.save(user=self.request.user)

    class Meta:
        model = Comment
        fields = ['pk', 'author', 'content', 'post', 'created_timestamp', 'modified_timestamp',]
    
class CommentViewSet(ext_mixins.NestedViewSetMixin, viewsets.ModelViewSet):
    queryset = Comment.objects.all().order_by('-created_timestamp')
    serializer_class = CommentSerializer
    pagination_class = StandardResultsSetPagination

    author = serializers.HiddenField(
        default=serializers.CurrentUserDefault(),
    )

    def create(self, request, *args, **kwargs):
        # print(f"PK: {request.user.id}")
        comment = Comment()
        comment.author = request.user
        serializer = self.serializer_class(comment, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

router = ext_routers.ExtendedDefaultRouter()
router.register(r'posts', PostViewSet) \
    .register(r'comments', CommentViewSet, 'posts-comment', parents_query_lookups=['post'])


blog/views/page.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.views import redirect_to_login
from django.contrib.auth.decorators import login_required, permission_required
from django.core.paginator import Paginator, EmptyPage
from blog.models import Post, Comment

def show_index(request):

	posts = Post.objects.all().order_by('-created_timestamp')
	paginator = Paginator(posts, 10)
	page_number = request.GET.get('page') or 1

	return render(request, "index-blog.html", {
		'posts': paginator.get_page(page_number)
	})

def view_post(request, id):

	post = Post.objects.get(pk=id)

	if not post:
		return HttpResponse(status=404)
	
	comments = Comment.objects.filter(post=post)

	return render(request, "post.html", {
		'post': post,
		'comments': comments,
	})

@permission_required('blog.create_post')
def create_post(request):

	return render(request, "post-create.html", {})

def edit_post(request, id):

	post = Post.objects.get(pk=id)

	if not post:
		return HttpResponse(status=404)
	
	# (request.user.has_perm('blog.delete_other_comment') or request.user.has_perm('blog.delete_self_comment'))

	if not (post.author == (request.user and request.user.has_perm('blog.change_self_post')) or request.user.has_perm('blog.change_other_post')):
		return redirect_to_login(request.path)
	
	return render(request, "post-edit.html", {
		'post': post
	})

blog/templates/base-blog.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}

<title>{% block title %}{% endblock title %} - Cleanify Blog</title>
<script defer src="{% static 'js/blog/main.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/blog/main.css' %}">

{% block meta-extra %}
{% endblock meta-extra %}

{% endblock meta %}

{% block content %}
<div class="container my-4">
	{% block content-blog %}
	{% endblock content-blog %}
</div>
{% endblock content %}

blog/templates/index-blog.html
{% extends 'base-blog.html' %}
{% load static markdown %}

{% block title %}
Blog
{% endblock title %}

{% block content-blog %}
<header class="mb-4">
	<h1>Cleanify Blog</h1>
	<p class="mb-3">Articles about waste and the enviroment, for aware readers.</p>
	{% if perms.blog.add_posts %}
	<a href='{% url "blog:create_post" %}' class="btn btn-primary">Create new post</a>
	{% endif %}	
</header>

<section id="posts">
	{% if not posts %}
	<p class="fst-italic">No posts for now. We are working on those!</p>
	{% endif %}
	{% for post in posts %}<article class="post-list">
		<header class="post-list-header article-header">
			<h2 itemprop="name headline" class="post-title mb-2 fw-bold"><a href='{% url "blog:view_post" post.pk %}' class="text-decoration-none text-body">{{ post.title }}</a></h2>
			<p class="text-muted post-info"><i class="bi bi-calendar-fill"></i> <time datetime='{{ post.timestamp | date:"c" }}' itemprop="datePublished">{{ post.created_timestamp | date:"d F Y" }}</time> • <i class="bi bi-person-fill"></i> {{ post.author }}</p>
		</header>
		<div itemprop="articleBody" class="post-content article-content">
			{{ post.content | markdown | safe }}
		</div>
		<p class="mt-3"><a href='{% url "blog:view_post" post.pk %}' class="post-list-read-more text-decoration-none">[read more]</a></p>
		<hr>
	</article>{% endfor %}	
</section>

{% if posts.paginator.num_pages != 1 %}

<div class="pagination d-flex justify-content-between align-items-center mt-2">
	<div class="prev">
		{% if posts.has_previous %}
			<a class="btn btn-primary me-2" href="?page=1"><i class="bi bi-arrow-left-square-fill"></i> first</a>
			<a class="btn btn-primary" href="?page={{ posts.previous_page_number }}"><i class="bi bi-arrow-left-circle-fill"></i> previous</a>
		{% endif %}
	</div>

	<div class="current">
		Page {{ posts.number }} of {{ posts.paginator.num_pages }}
	</div>

	<div class="next">
		{% if posts.has_next %}
			<a class="btn btn-primary" href="?page={{ posts.next_page_number }}">next <i class="bi bi-arrow-right-circle-fill"></i></a>
			<a class="btn btn-primary text-decoration-none ms-2" href="?page={{ posts.paginator.num_pages }}">last <i class="bi bi-arrow-right-square-fill"></i></a>
		{% endif %}
	</div>
</div>

{% endif %}

{% endblock content-blog %}

blog/templates/post-create.html
{% extends 'base-blog.html' %}
{% load static %}

{% block title %}
Create Post
{% endblock title %}

{% block content-blog %}

<script src="{% static 'js/blog/update-post.js' %}" defer></script>

<h2>Create new post</h2>

<form id="post-form" action="{% url 'blog:api_create_post' %}" data-redirect="{% url 'blog:view_post' 0 %}">
	<div class="mb-3">
		<label for="title-input" class="form-label fw-semibold">Title</label>
		<input type="text" class="form-control" id="title-input" name="title">
	</div>
	<div class="mb-3">
		<label for="content-input" class="form-label fw-semibold">Content</label>
		<textarea type="text" class="form-control expand" id="content-input" name="content"></textarea>
	</div>
	<button type="submit" class="btn btn-primary" id="add-submit">Create</button>
</form>

{% endblock content-blog %}

blog/templates/post-edit.html
{% extends 'base-blog.html' %}
{% load static %}

{% block title %}
Edit Post
{% endblock title %}

{% block content-blog %}

<script src="{% static 'js/blog/update-post.js' %}" defer></script>

<h2>Edit post</h2>

<form id="post-form" action="{% url 'blog:api_edit_post' post.pk %}" data-redirect="{% url 'blog:view_post' post.pk %}">
	<div class="mb-3">
		<label for="title-input" class="form-label fw-semibold">Title</label>
		<input type="text" class="form-control" id="title-input" name="title" value="{{ post.title }}">
	</div>
	<div class="mb-3">
		<label for="content-input" class="form-label fw-semibold">Content</label>
		<textarea type="text" class="form-control expand" id="content-input" name="content">{{ post.content }}</textarea>
	</div>
	<button type="submit" class="btn btn-primary" id="add-submit">Edit</button>
</form>

{% endblock content-blog %}

blog/templates/post.html
{% extends 'base-blog.html' %}
{% load static markdown %}

{% block title %}
{{ post.title }}
{% endblock title %}

{% block content-blog %}

<script src="https://cdn.jsdelivr.net/combine/npm/marked@4.1.1/marked.min.js,npm/dompurify@2.4.0" defer></script>
<script src="{% static 'js/blog/post.js' %}" defer></script>

<article itemscope itemtype="http://schema.org/BlogPosting" class="post-article">
	<header class="post-header article-header text-center">
		<h1 itemprop="name headline" class="post-title fw-bold display-4">{{ post.title }}</h1>
		<p class="text-muted post-info">
			<i class="bi bi-calendar-fill"></i> <time datetime='{{ post.timestamp | date:"c" }}' itemprop="datePublished">{{ post.created_timestamp | date:"d F Y" }}</time>
			• <i class="bi bi-person-fill"></i> <span itemprop="author">{{ post.author }}</span>
			{% if post.author == request.user and perms.blog.change_self_post or perms.blog.change_other_post %}
			• <a href='{% url "blog:edit_post" post.pk %}' class="text-decoration-none post-edit"><i class="bi bi-pencil-fill"></i> Edit Post</a>
			{% endif %}
			{% if post.author == request.user and perms.blog.delete_self_post or perms.blog.delete_other_post %}
			• <a href="#" data-action='{% url "blog:api_delete_post" post.pk %}' data-redirect='{% url "blog:index" %}' class="text-decoration-none text-danger post-delete"><i class="bi bi-trash-fill"></i> Delete Post</a>
			{% endif %}
		</p>
	</header>
	<div itemprop="articleBody" class="post-content article-content">
		{{ post.content | markdown | safe }}
	</div>
</article>

<hr>

<section id="comments">

	<h2>Comments</h2>

	{% if perms.blog.add_comment %}
	<form id="comment-new-form" method="post" action="{% url 'blog:api_create_comment' post.pk %}">
		<div class="mb-3">
			<textarea type="text" class="form-control expand" id="new-comment-input" name="content"></textarea>
		</div>
		<button type="submit" class="btn btn-primary" id="new-comment-submit">Send</button>
	</form>
	{% endif %}

	<div id="comments-list" class="mt-4" data-action='{% url "blog:posts-comment-list" post.pk %}'>
	</div>

	<p id="comments-no-comment" class="fst-italic">No comments.</p>

</section>

<template id="template-comment">
	<div class="comment card mt-2">
		<article itemscope itemtype="http://schema.org/Comment" class="card-body">
			<div class="comment-header">
				<p class="mb-2 text-bold comment-author" itemprop="author"></p>
				<p class="text-muted">
					<i class="bi bi-calendar-fill"></i> <time class="comment-timestamp" datetime='' itemprop="datePublished"></time>
					<span class="comment-edit-part">• <a href='#' class="text-decoration-none comment-edit"><i class="bi bi-pencil-fill"></i> Edit Comment</a></span>
					<span class="comment-delete-part">• <a href='#' class="text-decoration-none text-danger comment-delete" data-action='{% url "blog:api_delete_comment" post.pk 0 %}'><i class="bi bi-trash-fill"></i> Delete Comment</a></span>
				</p>
			</div>
			<div class="comment-content article-content">

				<!--  comment.content | markdown | safe  -->
			</div>
		</article>
	</div>
</template>

<template id="template-comment-edit">
	<div class="card-body">
		<div class="mb-3">
			<textarea type="text" class="form-control expand comment-edit-input" name="content"></textarea>
		</div>
		<button type="submit" class="btn btn-primary comment-edit-submit" data-action='{% url "blog:api_edit_comment" post.pk 0 %}'>Edit</button>
	</div>
</template>

{% endblock content-blog %}