authc/urls.py
from django.urls import path
from .views import registration_view, login_view, logout_view, api_login, api_logout, api_register, api_info

app_name = 'authc'

urlpatterns = [
    path('register/',registration_view, name='register'),
    path('login/',login_view, name='login'),
    path('logout/',logout_view, name='logout'),
    path('api/login', api_login, name='api_login'),
    path('api/logout', api_logout, name='api_logout'),
    path('api/register', api_register, name='api_register'),
    path('api/info', api_info, name='api_info') 
]

crewdashboard/urls.py
from django.urls import path
from crewdashboard.views import add_new_locations, show_locations, show_json, delete_card, flutter_showJson, flutter_addLocation
app_name = 'crewdashboard'

urlpatterns = [
    path('', add_new_locations, name='addlocation'),
    path('dashboard/', show_locations, name='show_locations'),
    path('dashboard/', show_locations, name='show_locations_admin'),
    path('json/', show_json, name='json'),
    path('delete/', delete_card, name='delete_card'),
    path('reportlocation/', flutter_addLocation, name='addlocationflutter'),
    path('locations/', flutter_showJson, name='jsonflutter')
]

faq/urls.py
from django.urls import path
from .views import index, json, add, update_thumbsUp,  Add_from_flutter

app_name = 'faq'
urlpatterns = [
    path('', index, name='index'),
    path('json/', json, name='json'),
    path('add/', add, name='add'),
    path('thumbsup/', update_thumbsUp, name='update_thumbsUp'),
    path('addFlutter/', Add_from_flutter, name ='Add_from_flutter')

]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('bank/', include('banksampah.urls')),
    path('blog/', include('blog.urls')),
    path('faq/', include('faq.urls')),
    path('auth/', include('authc.urls')),
    path('report/', include('crewdashboard.urls')),
]


crewdashboard/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils import timezone

class Location(models.Model):
    date= models.DateField(default=timezone.now)
    location = models.CharField(max_length=200, null=True)
    urgency= models.IntegerField(
        null =True, 
        validators=[
            MaxValueValidator(5),
            MinValueValidator(1)
        ])
    description= models.TextField(null=True, blank=True)

    def __str__(self):
        return self.description

crewdashboard/forms.py
from django import forms
from crewdashboard.models import Location

class FormReport(forms.ModelForm):
    class Meta:
        model = Location
        fields = ["date", "location", "urgency", "description"]

    def __str__(self):
        return ""

crewdashboard/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required, user_passes_test, permission_required
from django.http import HttpResponse
from django.core import serializers
from .models import Location
import datetime
from django.views.decorators.csrf import csrf_exempt
from .forms import FormReport
from django.shortcuts import redirect
from django.core import serializers
from django.http.response import HttpResponse, JsonResponse

# Create your views here.

@permission_required('crewdashboard.view_location')
def show_locations(request):
    return render(request, "dashboard.html")

@permission_required('crewdashboard.delete_location')
def delete_card(request):
    if request.method == "POST":
        card = Location.objects.get(id=request.POST["id"])
        card.delete()
    return redirect('todolist:show_todolist')

@csrf_exempt
@permission_required('crewdashboard.view_location')
def show_json(request):
    data = Location.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@csrf_exempt
@permission_required('crewdashboard.add_location')
def add_new_locations(request):
    context ={}
    context['form']= FormReport()
    if request.method == 'POST':
        location = request.POST.get('location')
        urgency = request.POST.get('urgency')
        description = request.POST.get('description')
        new_location = Location(
            date = datetime.datetime.now(),
            location = location,
            urgency = urgency,
            description = description,
        )
        new_location.save()
    return render(request, 'locations.html', context)

@csrf_exempt
def flutter_addLocation(request):
    try:
        location = request.POST.get('location')
        urgency = request.POST.get('urgency')
        description = request.POST.get('description')
        new_location = Location(
            date = datetime.datetime.now(),
            location = location,
            urgency = urgency,
            description = description,
        )
        new_location.save() 
        response_data = {
        'date' : datetime.datetime.now(),
        'location': request.POST.get('location'),
        'urgency': request.POST.get('urgency'),
        'description' :request.POST.get('description')}
        return JsonResponse(response_data)

    except:
        print("salah")
        return JsonResponse({"message": "Failed!"})

@csrf_exempt
def flutter_showJson(request):
    data = Location.objects.all()
    serialize = serializers.serialize('json', data)
    response = {
        'locations': serialize,
    }
    return JsonResponse(response)

crewdashboard/templates/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Waste Report Dashboard - Cleanify</title>
<script>
    window.JSON_URL = "{% url 'crewdashboard:json' %}"
</script>
<script defer src="{% static 'js/report/dashboard.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/report/dashboard.css' %}"></link>
{% endblock meta %}

{% block content %}
<div class="container my-4" id="container">

    <h2 class="text-center fst-italic mt-4 mb-4">Cleaning Crews, We Need Your Help!</h2>

    <div id="card" class="card align-items-center justify-content-center py-2 mb-4">
        <form class="text-center" method="POST">
            {% csrf_token %}
            <div class="d-flex flex-start justify-content-around" id="card-deck" style="flex-wrap: wrap">
            </div>
        </form>
    </div>
    <div class="text-center">
        <a href="{% url 'authc:logout' %}" class="btn btn-primary">Logout</a>
    </div>

</div>

<style>

</style>

{% endblock content %}

crewdashboard/templates/locations.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Report Waste - Cleanify</title>
<script>
    window.ADD_ENDPOINT = "{% url 'crewdashboard:addlocation' %}"
</script>
<script defer src="{% static 'js/report/form.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/report/form.css' %}">
{% endblock meta %}

{% block content %}
<div class="container-fluid my-4">
    <h2 class="text-center fst-italic">Welcome, {{ user }}!</h2>

    <form method="POST" id="form_post" action="" entype="multipart/form-data">
        {% csrf_token %}
        <tr>
            <div class="form-group mt-3">
                <label class="heading-5" for="location">Address </label>
                <input id="location" type="text" name="location" placeholder="Need-to-Clean Location" class="form-control" minlength="10" required>
            </div>
        </tr>

        <tr>
            <div class="form-group mt-3">
                <label class="heading-5" for="urgency">Urgency </label>
                <input id="urgency" type="number" name="urgency" placeholder="Urgency level out of 5" class="form-control" min="1" max="5" required>
            </div>
        </tr>

        <tr>
            <div class="form-group mt-3">
                <label class="heading-5" for="description">Description </label>
                <input id="description" type="text" name="description" placeholder="Description" class="form-control" minlength="10" required>
            </div>
        </tr>

        <div class="button mt-3">
            <button id="submit" type="submit" class="btn btn-primary d-flex mx-auto" onclick="clear()">Submit</button>
        </div>
    </form>
</div>

{% endblock content %}