faq/urls.py
from django.urls import path
from .views import index, json, add, update_thumbsUp,  Add_from_flutter

app_name = 'faq'
urlpatterns = [
    path('', index, name='index'),
    path('json/', json, name='json'),
    path('add/', add, name='add'),
    path('thumbsup/', update_thumbsUp, name='update_thumbsUp'),
    path('addFlutter/', Add_from_flutter, name ='Add_from_flutter')

]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('bank/', include('banksampah.urls')),
    path('blog/', include('blog.urls')),
    path('faq/', include('faq.urls')),
    path('auth/', include('authc.urls')),
    path('report/', include('crewdashboard.urls')),
]


faq/models.py
from django.db import models

# Create your models here.
class FAQ(models.Model) :
    question = models.CharField(max_length=400)
    answer = models.TextField()
    thumbsUp = models.IntegerField(default=0)

faq/forms.py
from django import forms
from .models import FAQ

class FAQForm(forms.ModelForm):
    class Meta:
        model = FAQ
        fields = ['q', 'a']
    
    q_attrs = {
        'type':'text',
        'placeholder':'Ask your question here',
        'class':'form-control'
    }

    a_attrs = {
        'type':'text',
        'placeholder':'Input your answer here',
        'class':'form-control'
    }

    q = forms.CharField(label="Question",required=True, max_length=400, widget=forms.TextInput(attrs=q_attrs))
    a = forms.CharField(label="Answer",required=True, widget=forms.Textarea(attrs=a_attrs))

faq/views.py
from django.shortcuts import render
from .models import FAQ
from .forms import FAQForm
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.http import QueryDict
from django.core import serializers
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required, permission_required
import json
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
# @permission_required('faq.view_faq')
def index(request):
    faqs = FAQ.objects.order_by('-thumbsUp')
    context = {'faqs': faqs}
    return render(request, 'faq.html', context)

# @permission_required('faq.view_faq')
def json(request):
    # sort according to thumbs up
    data = serializers.serialize('json', FAQ.objects.order_by('-thumbsUp'))

    return HttpResponse(data, content_type="application/json")

@login_required
@permission_required('faq.update_faq')
def update_thumbsUp(request):
    pk = request.POST.get('pk')
    faq = FAQ.objects.get(pk=pk)

    # update thumbs up
    faq.thumbsUp += 1
    faq.save(update_fields=['thumbsUp'])

    # sorting
    data = serializers.serialize('json', FAQ.objects.order_by('-thumbsUp'))

    return HttpResponseRedirect('/faq')

@permission_required('faq.add_faq')
def add(request):
    if request.method == 'POST':
        form = FAQForm(request.POST)
        if form.is_valid():
            question = form.cleaned_data['q']
            answer = form.cleaned_data['a']
            FAQ.objects.create(question = question, answer = answer)
            return HttpResponseRedirect('/faq')
    else:
        form = FAQForm()

    return render(request, 'faq-form.html', {'form': form})

@csrf_exempt
@permission_required('faq.add_faq')
def Add_from_flutter(request):
    if request.method == 'POST':

        new_FAQ = FAQ.objects.create(
            question = request.POST['q'],
            answer = request.POST['a'],
        )

        new_FAQ.save()


    return JsonResponse({"instance": "FAQ berhasil ditambahkan"}, status=200)

faq/templates/faq-form.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Add New Question - Cleanify</title>
<link rel="stylesheet" href="{% static 'css/faq/main.css' %}">
{% endblock meta %}

{% block content %}

<div class="container text-white my-4">
    <h1 class="text-center fw-bold mb-4">Add New Question</h1>
    <form action="" method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label for="question" class="form-label fw-bold">Question</label>
            {{form.q}}
        </div>
        <div class="mb-3">
            <label for="answer" class="form-label fw-bold">Answer</label>
            {{form.a}}
        </div>
        <button type="submit" class="btn btn-success" id="btn-add">Add FAQ</button>
    </form>
</div>

{% endblock content %}

faq/templates/faq.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Frequently Asked Questions - Cleanify</title>
<script>
    window.THUMBS_UP_ENDPOINT = "{% url 'faq:update_thumbsUp' %}"
</script>
<script defer src="{% static 'js/faq/list.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/faq/main.css' %}">
{% endblock meta %}

{% block content %}
<div class="container text-white my-4">
    <h1 class="text-center fw-bold">Frequently Asked Questions</h1>
    <br>
    <div class="faq-container">
        {% for faq in faqs %}
        <div class="card text-body">
            <h5 class="card-header fw-bold">{{faq.question}}</h5>
            <div class="card-body">
                <p class="card-text">{{faq.answer}}</p>
                <a class="btn btn-success thumbsUp fw-bold" data-pk="{{faq.pk}}">
                    {{faq.thumbsUp}} Thumbs Up
                </a>
            </div>
        </div>
        <br>
        {% endfor %}
    </div>
    {% if perms.add_faq %}
    <a class="btn btn-success fw-bold" href="{% url 'faq:add' %}">
        Add New Question
    </a>
    {% endif %}

</div>

{% endblock content %}