authc/urls.py
from django.urls import path
from .views import registration_view, login_view, logout_view, api_login, api_logout, api_register, api_info

app_name = 'authc'

urlpatterns = [
    path('register/',registration_view, name='register'),
    path('login/',login_view, name='login'),
    path('logout/',logout_view, name='logout'),
    path('api/login', api_login, name='api_login'),
    path('api/logout', api_logout, name='api_logout'),
    path('api/register', api_register, name='api_register'),
    path('api/info', api_info, name='api_info') 
]

banksampah/urls.py
from banksampah.views import create_bank, show_bank, delete_bank, show_banksampah_json, flutter_createbank, show_bank_flutter, show_banksampah_json_flutter, delete_bankflutter
from django.urls import path

app_name = 'banksampah'

urlpatterns = [
    path('', create_bank, name='create'),
    path('contents/', show_bank, name='show'),
    path('delete/<int:id>/', delete_bank, name='delete'),
    path('json/', show_banksampah_json, name='show_json'),
    path('createbank_flutter/', flutter_createbank, name='createbankflutter'),
    path('contents_flutter/', show_bank_flutter, name='show_flutter'),
    path('json_flutter/', show_banksampah_json_flutter, name='show_json_flutter'),
    path('delete_flutter/<int:id>/', delete_bankflutter, name='delete_flutter'),
]

blog/urls.py
from django.urls import path, include
from .views import api, api2, page
app_name = 'blog'

urlpatterns = [
	path('', page.show_index, name='index'),
	path('new/', page.create_post, name='create_post'),
	path('<int:id>/', page.view_post, name='view_post'),
	path('<int:id>/edit', page.edit_post, name='edit_post'),
    
    path('api2/', include(api2.router.urls)),
    
	path('api/post', api.list_posts, name='api_list_posts'),
	path('api/post/new', api.create_post, name='api_create_post'),
	path('api/post/<int:post_id>', api.get_post, name='api_get_post'),
    path('api/post/<int:post_id>/edit', api.edit_post, name="api_edit_post"),
    path('api/post/<int:post_id>/delete', api.delete_post, name="api_delete_post"),
	path('api/post/<int:post_id>/comment', api.list_comments, name="api_list_comments"),
	path('api/post/<int:post_id>/comment/new', api.create_comment, name="api_create_comment"),
    path('api/post/<int:post_id>/comment/<int:comment_id>', api.get_comment, name="api_get_comment"),
    path('api/post/<int:post_id>/comment/<int:comment_id>/edit', api.edit_comment, name="api_edit_comment"),
    path('api/post/<int:post_id>/comment/<int:comment_id>/delete', api.delete_comment, name="api_delete_comment")
]

faq/urls.py
from django.urls import path
from .views import index, json, add, update_thumbsUp,  Add_from_flutter

app_name = 'faq'
urlpatterns = [
    path('', index, name='index'),
    path('json/', json, name='json'),
    path('add/', add, name='add'),
    path('thumbsup/', update_thumbsUp, name='update_thumbsUp'),
    path('addFlutter/', Add_from_flutter, name ='Add_from_flutter')

]

index/urls.py
from django.urls import path
from .views import index_page

app_name = 'index'

urlpatterns = [
	path('', index_page, name='index_page'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('bank/', include('banksampah.urls')),
    path('blog/', include('blog.urls')),
    path('faq/', include('faq.urls')),
    path('auth/', include('authc.urls')),
    path('report/', include('crewdashboard.urls')),
]


templates/base-blank.html
<!DOCTYPE html>
<html lang="en">

<head>
	{% include "header.html" %}
	{% block meta %}{% endblock meta %}
</head>

<body>
	{% block content %}{% endblock content %}
</body>

</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
	{% include "head.html" %}
	{% block meta %}{% endblock meta %}
</head>

<body>
	{% include "navbar.html" %}
	{% block app-navbar %}{% endblock app-navbar %}
	<main>
		{% block content %}{% endblock content %}
	</main>
	{% include "footer.html" %}
</body>

</html>

templates/footer.html
<footer class="footer text-bg-dark">
	<div class="container py-3">
		<p class="mb-0">Made with ♥ by Group A03 for Platform-based Programming, Odd Semester 2022/2023. <br/><a href="https://github.com/A03-PBP-2022/cleanify" class="text-decoration-none">View the code.</a></p>
	</div>
</footer>

templates/head.html
{% load static %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
<script src="https://cdn.jsdelivr.net/npm/jquery@3.6.1/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" defer></script>
<script>
	window.CSRF_TOKEN = "{{ csrf_token }}"
</script>
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black">
<meta name="apple-mobile-web-app-title" content="Cleanify">
<link rel="apple-touch-icon" href="{% static 'img/icons/Icon-192.png' %}">
<link rel="icon" href="{% static 'favicon.ico' %}" sizes="any">
<link rel="apple-touch-icon" href="{% static 'img/icons/apple-touch-icon.png' %}">

templates/navbar.html
<nav class="navbar navbar-dark navbar-expand-xl bg-cleanify">
	<div class="container">
		<a class="navbar-brand fs-3" href='{% url "index:index_page" %}'><i class="bi bi-trash-fill"></i> Cleanify</a>
		<button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
			<div class="offcanvas-header">
				<h5 class="offcanvas-title" id="offcanvasNavbarLabel"><i class="bi bi-trash-fill"></i> Cleanify</h5>
				<button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
			</div>
			<div class="offcanvas-body">
				<ul class="navbar-nav justify-content-end flex-grow-1">

					{% if perms.crewdashboard.add_location and perms.crewdashboard.view_location %}
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="offcanvasNavbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
							<i class="bi bi-megaphone-fill"></i> Waste Report
						</a>
						<ul class="dropdown-menu" aria-labelledby="offcanvasNavbarDropdown">
							<li><a class="dropdown-item" href='{% url "crewdashboard:addlocation" %}'>Report Location</a></li>
							<li><a class="dropdown-item" href='{% url "crewdashboard:show_locations" %}'>View Locations</a></li>
						</ul>
					</li>
					{% elif perms.crewdashboard.add_location %}
					<li class="nav-item">
						<a class="nav-link" href='{% url "crewdashboard:addlocation" %}'><i class="bi bi-megaphone-fill"></i> Report Waste</a>
					</li>
					{% elif perms.crewdashboard.view_location %}
					<li class="nav-item">
						<a class="nav-link" href='{% url "crewdashboard:show_locations" %}'><i class="bi bi-megaphone-fill"></i> View Waste Reports</a>
					</li>
					{% endif %}

					{% if perms.banksampah.add_bank and perms.banksampah.view_bank %}
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="offcanvasNavbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
							<i class="bi bi-bank2"></i> Waste Bank
						</a>
						<ul class="dropdown-menu" aria-labelledby="offcanvasNavbarDropdown">
							<li><a class="dropdown-item" href='{% url "banksampah:create" %}'>Add Waste</a></li>
							<li><a class="dropdown-item" href='{% url "banksampah:show" %}'>View Bank</a></li>
						</ul>
					</li>
					{% endif %}

					{% if perms.faq.add_faq %}
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="offcanvasNavbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
							<i class="bi bi-question-circle-fill"></i> FAQ
						</a>
						<ul class="dropdown-menu" aria-labelledby="offcanvasNavbarDropdown">
							<li><a class="dropdown-item" href='{% url "faq:index" %}'>View List</a></li>
							<li><a class="dropdown-item" href='{% url "faq:add" %}'>Add New</a></li>
						</ul>
					</li>
					{% else %}
					<li class="nav-item">
						<a class="nav-link" href='{% url "faq:index" %}'><i class="bi bi-question-circle-fill"></i> FAQ</a>
					</li>
					{% endif %}

					{% if perms.blog.add_post %}
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="offcanvasNavbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
							<i class="bi bi-newspaper"></i> Blog
						</a>
						<ul class="dropdown-menu" aria-labelledby="offcanvasNavbarDropdown">
							<li><a class="dropdown-item" href='{% url "blog:index" %}'>Index</a></li>
							<li><a class="dropdown-item" href='{% url "blog:create_post" %}'>Create Post</a></li>
						</ul>
					</li>
					{% else %}
					<li class="nav-item">
						<a class="nav-link" href='{% url "blog:index" %}'><i class="bi bi-newspaper"></i> Blog</a>
					</li>
					{% endif %}

					{% if request.user.is_authenticated %}
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="offcanvasNavbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
							<i class="bi bi-person-fill"></i> {{ request.user }}
						</a>
						<ul class="dropdown-menu" aria-labelledby="offcanvasNavbarDropdown">
							<li><a class="dropdown-item" href='{% url "authc:logout" %}'>Logout</a></li>
						</ul>
					</li>
					{% else %}
					<li class="nav-item">
						<a class="nav-link" href='{% url "authc:login" %}'>Login</a>
					</li>
					{% endif %}
				</ul>
			</div>
		</div>
	</div>
</nav>